######################################################################
# Automatically generated by qmake (3.0) Mon Jun 27 16:38:55 2016
######################################################################

TEMPLATE = app
TARGET = qtdemo
INCLUDEPATH += .

# Input
SOURCES += test.cpp

QT += widgets
