######################################################################
# Automatically generated by qmake (3.0) Mon Jun 27 16:51:11 2016
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
SOURCES += test.cpp
