######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 20 19:28:04 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
