######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 20 18:12:11 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += helloQT.cpp test.cpp
